baseurl = "https://pollitosabroson.gitlab.io"
title = "Alejandro Rosales"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Alejandro Rosales"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "Alejandro Rosales"
  email = "Jose.alejandro.her.ros@gmail.com"
  Ganalytics = "UA-8596932-4"



[[params.social]]
  title = "twitter"
  url = "https://twitter.com/pollitosabroson"
[[params.social]]
  title = "github"
  url = "https://github.com/pollitosabroson"
[[params.social]]
  title = "gitlab"
  url = "https://gitlab.com/pollitosabroson"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -160